language: python
matrix:
  fast_finish: true
  include:
    - python: 3.3
      env: TOXENV=py33 COVERAGE_ID=travis-ci
    - python: 3.4
      env: TOXENV=py34 COVERAGE_ID=travis-ci
    - python: 3.5
      env: TOXENV=py35 COVERAGE_ID=travis-ci
    # some errors only present themselves when using with ASYNCIODEBUG,
    # especially exceptions in tasks and so on.
    - python: 3.5
      env: ASYNCIODEBUG=1 TOXENV=py35 COVERAGE_ID=travis-ci
install:
  - pip install tox
script:
  - tox

notifications:
  email:
    recipients:
      - contact@jeffquast.com
    on_success: change
    on_failure: change

sudo: false
#addons:
#  apt:
#    packages:
#      - telnet
#      - curl
#      - netcat-openbsd
#      - tintin++
